ci: consolidate deployment and test into one workflow

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,13 +1,104 @@
-# Re-usable workflow to run tests
+# Re-usable workflow to test deployments
 name: Test
-
 on:
   workflow_call:
   workflow_dispatch:
-  schedule:
-    - cron: '0 11 * * 0'
+  # schedule:
+  #   - cron: '0 12 * * 0'
 
 jobs:
+
+  # ---------------------------------------------------------------------------
+  # Build Docker Image
+
+  build:
+    uses: ./.github/workflows/build.yml
+
+  # ---------------------------------------------------------------------------
+  # Deployment Modes
+
+  deployment:
+
+    needs: build
+    if: ${{ always() }}
+
+    runs-on: ubuntu-latest
+    timeout-minutes: 60
+
+    env:
+      DOCKER_BUILDKIT: 1
+
+    strategy:
+      fail-fast: false
+      matrix:
+        mode: [quickstart, development, production, testing]
+
+    steps:
+
+      - name: Download Build Output
+        uses: actions/download-artifact@v8
+        with:
+          name: breedbase-docker
+          path: breedbase.tar
+
+      # parse tag from load output, PR have unusual formats, also sometimes multiple tags
+      - name: Load Docker Image
+        run: |
+          load=$(docker load --input breedbase.tar | tee /dev/stderr)
+          echo -e $load
+          TAG=$(echo -e $load | sed 's/Loaded image: //g' | head -n 1 | cut -d ":" -f 2 | cut -d " " -f 1)
+          echo DOCKER_TAG="$TAG" >> $GITHUB_ENV
+
+      - name: Checkout breedbase_dockerfile repo
+        uses: actions/checkout@v6
+        with:
+          submodules: true
+          fetch-depth: 1
+
+      - name: Link compose file
+        run: |
+          ln -s compose.yml compose.quickstart.yml
+
+      - name: Setup
+        run: ./setup
+
+      # ---------------------------------------------------------------------------
+      # Deployments
+
+      - name: Build supporting images
+        run: docker compose -f compose.${{ matrix.mode }}.yml build --no-cache
+
+      - name: Start containers
+        run: docker compose -f compose.${{ matrix.mode }}.yml up -d
+
+      - name: Healthcheck containers
+        uses: stringbean/docker-healthcheck-action@v3
+        with:
+          container: ${{ matrix.mode }}-breedbase-1
+          wait-time: 300
+          require-status: running
+          require-healthy: true
+
+      - name: Breedbase DB container log
+        if: always()
+        run: docker compose -f compose.${{ matrix.mode }}.yml logs breedbase_db
+
+      - name: Breedbase Web container log
+        if: always()
+        run: docker compose -f compose.${{ matrix.mode }}.yml logs breedbase
+
+      - name: Keycloak Web container log
+        if: ${{ (matrix.mode == 'testing') || (matrix.mode == 'development') }}
+        run: docker compose -f compose.${{ matrix.mode }}.yml logs keycloak
+
+      - name: Stop containers
+        run: docker compose down
+
+      - name: Clean volumes
+        run: docker volume prune -af
+
+      - name: Clean data
+        run: rm -rf data
 
   # ---------------------------------------------------------------------------
   # Test Suite
@@ -21,36 +112,22 @@ jobs:
 
     strategy:
       fail-fast: false
-      # matrix:
-      #   subtest_key:
-      #     - unit
-      #     - unit_fixture
-      #     - unit_mech
-      #     - selenium2_list
-      #     - selenium2_trial
-      #     - selenium2_dataset
-      #     - selenium2_authenticate
-      #     - selenium2_breeders
-      #     - selenium2_onto
-      #     - selenium2_search
-      #     - selenium2_stock
-      #     - selenium2_tools
+      matrix:
+        subtest_key:
+          - unit
+          - unit_fixture
+          - unit_mech
+          - selenium2_list
+          - selenium2_trial
+          - selenium2_dataset
+          - selenium2_authenticate
+          - selenium2_breeders
+          - selenium2_onto
+          - selenium2_search
+          - selenium2_stock
+          - selenium2_tools
 
     steps:
-      - name: Free Disk Space (Ubuntu)
-        uses: jlumbroso/free-disk-space@main
-        with:
-          # this might remove tools that are actually needed,
-          # when set to "true" but frees about 6 GB
-          tool-cache: true
-
-          # all of these default to true, but feel free to set to
-          # "false" if necessary for your workflow
-          android: true
-          dotnet: true
-          haskell: false
-          large-packages: false
-          swap-storage: false
 
       - name: Checkout breedbase_dockerfile repo
         uses: actions/checkout@v6
@@ -60,12 +137,6 @@ jobs:
 
       - name: Setup
         run: ./setup
-
-      - uses: nick-fields/retry@v3
-        with:
-          timeout_minutes: 20
-          max_attempts: 3
-          command: docker build -t bffafirms/breedbase:latest .
 
       - name: Build supporting images
         run: docker compose -f compose.testing.yml build --no-cache
@@ -79,80 +150,90 @@ jobs:
           ./run_test -s t/unit/CXGN/String
           exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      - name: Debug solgwas
+      - name: Run unit tests
+        if: ${{ matrix.subtest_key == 'unit' }}
         run: |
-          ./run_test -s t/unit_mech/AJAX/Solgwas.t
+          ./run_test t/unit
           exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run unit tests
-      #   if: ${{ matrix.subtest_key == 'unit' }}
-      #   run: |
-      #     ./run_test t/unit
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run fixture tests
+        if: ${{ matrix.subtest_key == 'unit_fixture' }}
+        run: |
+          ./run_test t/unit_fixture
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run fixture tests
-      #   if: ${{ matrix.subtest_key == 'unit_fixture' }}
-      #   run: |
-      #     ./run_test t/unit_fixture
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run mech tests
+        if: ${{ matrix.subtest_key == 'unit_mech' }}
+        run: |
+          ./run_test t/unit_mech
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run mech tests
-      #   if: ${{ matrix.subtest_key == 'unit_mech' }}
-      #   run: |
-      #     ./run_test t/unit_mech
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      # Run all selenium tests individually to avoid solgs for now
+      - name: Run selenium tests lists
+        if: ${{ matrix.subtest_key == 'selenium2_list' }}
+        run: |
+          ./run_test t/selenium2/01_list
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # # Run all selenium tests individually to avoid solgs for now
-      # - name: Run selenium tests lists
-      #   if: ${{ matrix.subtest_key == 'selenium2_list' }}
-      #   run: |
-      #     ./run_test t/selenium2/01_list
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests trial
+        if: ${{ matrix.subtest_key == 'selenium2_trial' }}
+        run: |
+          ./run_test t/selenium2/02_trial
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests trial
-      #   if: ${{ matrix.subtest_key == 'selenium2_trial' }}
-      #   run: |
-      #     ./run_test t/selenium2/02_trial
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests dataset
+        if: ${{ matrix.subtest_key == 'selenium2_dataset' }}
+        run: |
+          ./run_test t/selenium2/03_dataset
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests dataset
-      #   if: ${{ matrix.subtest_key == 'selenium2_dataset' }}
-      #   run: |
-      #     ./run_test t/selenium2/03_dataset
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests authenticate
+        if: ${{ matrix.subtest_key == 'selenium2_authenticate' }}
+        run: |
+          ./run_test t/selenium2/authenticate
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests authenticate
-      #   if: ${{ matrix.subtest_key == 'selenium2_authenticate' }}
-      #   run: |
-      #     ./run_test t/selenium2/authenticate
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests breeders
+        if: ${{ matrix.subtest_key == 'selenium2_breeders' }}
+        run: |
+          ./run_test t/selenium2/breeders
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests breeders
-      #   if: ${{ matrix.subtest_key == 'selenium2_breeders' }}
-      #   run: |
-      #     ./run_test t/selenium2/breeders
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests onto
+        if: ${{ matrix.subtest_key == 'selenium2_onto' }}
+        run: |
+          ./run_test t/selenium2/onto
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests onto
-      #   if: ${{ matrix.subtest_key == 'selenium2_onto' }}
-      #   run: |
-      #     ./run_test t/selenium2/onto
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests search
+        if: ${{ matrix.subtest_key == 'selenium2_search' }}
+        run: |
+          ./run_test t/selenium2/search
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests search
-      #   if: ${{ matrix.subtest_key == 'selenium2_search' }}
-      #   run: |
-      #     ./run_test t/selenium2/search
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests stock
+        if: ${{ matrix.subtest_key == 'selenium2_stock' }}
+        run: |
+          ./run_test t/selenium2/stock
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests stock
-      #   if: ${{ matrix.subtest_key == 'selenium2_stock' }}
-      #   run: |
-      #     ./run_test t/selenium2/stock
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+      - name: Run selenium tests tools
+        if: ${{ matrix.subtest_key == 'selenium2_tools' }}
+        run: |
+          ./run_test t/selenium2/tools
+          exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
 
-      # - name: Run selenium tests tools
-      #   if: ${{ matrix.subtest_key == 'selenium2_tools' }}
-      #   run: |
-      #     ./run_test t/selenium2/tools
-      #     exit $(docker inspect testing-breedbase-1 --format='{{.State.ExitCode}}')
+  # ---------------------------------------------------------------------------
+  # Cleanup
+
+  cleanup:
+
+    needs: [deployment]
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Delete Docker iamge
+        uses: geekyeggo/delete-artifact@v6
+        with:
+            name: breedbase-docker
